//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityCodeFirstConsola
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ejercicioEntities : DbContext
    {
        public ejercicioEntities()
            : base("name=ejercicioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<puesto> puesto { get; set; }
        public virtual DbSet<sueldo> sueldo { get; set; }
        public virtual DbSet<trabajador> trabajador { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
