//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityCodeFirstConsola
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public int id_pagos { get; set; }
        public int id_trabajador { get; set; }
        public int id_puesto { get; set; }
        public System.DateTime fechapago { get; set; }
        public int semanas { get; set; }
        public double montopago { get; set; }
    
        public virtual puesto puesto { get; set; }
        public virtual trabajador trabajador { get; set; }
    }
}
