#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ejercicio")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertpagos(pagos instance);
    partial void Updatepagos(pagos instance);
    partial void Deletepagos(pagos instance);
    partial void Insertusuarios(usuarios instance);
    partial void Updateusuarios(usuarios instance);
    partial void Deleteusuarios(usuarios instance);
    partial void Insertpuesto(puesto instance);
    partial void Updatepuesto(puesto instance);
    partial void Deletepuesto(puesto instance);
    partial void Insertsueldo(sueldo instance);
    partial void Updatesueldo(sueldo instance);
    partial void Deletesueldo(sueldo instance);
    partial void Inserttrabajador(trabajador instance);
    partial void Updatetrabajador(trabajador instance);
    partial void Deletetrabajador(trabajador instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LINQ6.Properties.Settings.Default.ejercicioConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<pagos> pagos
		{
			get
			{
				return this.GetTable<pagos>();
			}
		}
		
		public System.Data.Linq.Table<usuarios> usuarios
		{
			get
			{
				return this.GetTable<usuarios>();
			}
		}
		
		public System.Data.Linq.Table<puesto> puesto
		{
			get
			{
				return this.GetTable<puesto>();
			}
		}
		
		public System.Data.Linq.Table<sueldo> sueldo
		{
			get
			{
				return this.GetTable<sueldo>();
			}
		}
		
		public System.Data.Linq.Table<trabajador> trabajador
		{
			get
			{
				return this.GetTable<trabajador>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pagos")]
	public partial class pagos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pagos;
		
		private int _id_trabajador;
		
		private int _id_puesto;
		
		private System.DateTime _fechapago;
		
		private int _semanas;
		
		private double _montopago;
		
		private EntityRef<puesto> _puesto;
		
		private EntityRef<trabajador> _trabajador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pagosChanging(int value);
    partial void Onid_pagosChanged();
    partial void Onid_trabajadorChanging(int value);
    partial void Onid_trabajadorChanged();
    partial void Onid_puestoChanging(int value);
    partial void Onid_puestoChanged();
    partial void OnfechapagoChanging(System.DateTime value);
    partial void OnfechapagoChanged();
    partial void OnsemanasChanging(int value);
    partial void OnsemanasChanged();
    partial void OnmontopagoChanging(double value);
    partial void OnmontopagoChanged();
    #endregion
		
		public pagos()
		{
			this._puesto = default(EntityRef<puesto>);
			this._trabajador = default(EntityRef<trabajador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pagos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pagos
		{
			get
			{
				return this._id_pagos;
			}
			set
			{
				if ((this._id_pagos != value))
				{
					this.Onid_pagosChanging(value);
					this.SendPropertyChanging();
					this._id_pagos = value;
					this.SendPropertyChanged("id_pagos");
					this.Onid_pagosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trabajador", DbType="Int NOT NULL")]
		public int id_trabajador
		{
			get
			{
				return this._id_trabajador;
			}
			set
			{
				if ((this._id_trabajador != value))
				{
					if (this._trabajador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_trabajadorChanging(value);
					this.SendPropertyChanging();
					this._id_trabajador = value;
					this.SendPropertyChanged("id_trabajador");
					this.Onid_trabajadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_puesto", DbType="Int NOT NULL")]
		public int id_puesto
		{
			get
			{
				return this._id_puesto;
			}
			set
			{
				if ((this._id_puesto != value))
				{
					if (this._puesto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_puestoChanging(value);
					this.SendPropertyChanging();
					this._id_puesto = value;
					this.SendPropertyChanged("id_puesto");
					this.Onid_puestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechapago", DbType="Date NOT NULL")]
		public System.DateTime fechapago
		{
			get
			{
				return this._fechapago;
			}
			set
			{
				if ((this._fechapago != value))
				{
					this.OnfechapagoChanging(value);
					this.SendPropertyChanging();
					this._fechapago = value;
					this.SendPropertyChanged("fechapago");
					this.OnfechapagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semanas", DbType="Int NOT NULL")]
		public int semanas
		{
			get
			{
				return this._semanas;
			}
			set
			{
				if ((this._semanas != value))
				{
					this.OnsemanasChanging(value);
					this.SendPropertyChanging();
					this._semanas = value;
					this.SendPropertyChanged("semanas");
					this.OnsemanasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montopago", DbType="Float NOT NULL")]
		public double montopago
		{
			get
			{
				return this._montopago;
			}
			set
			{
				if ((this._montopago != value))
				{
					this.OnmontopagoChanging(value);
					this.SendPropertyChanging();
					this._montopago = value;
					this.SendPropertyChanged("montopago");
					this.OnmontopagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="puesto_pagos", Storage="_puesto", ThisKey="id_puesto", OtherKey="id_puesto", IsForeignKey=true)]
		public puesto puesto
		{
			get
			{
				return this._puesto.Entity;
			}
			set
			{
				puesto previousValue = this._puesto.Entity;
				if (((previousValue != value) 
							|| (this._puesto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._puesto.Entity = null;
						previousValue.pagos.Remove(this);
					}
					this._puesto.Entity = value;
					if ((value != null))
					{
						value.pagos.Add(this);
						this._id_puesto = value.id_puesto;
					}
					else
					{
						this._id_puesto = default(int);
					}
					this.SendPropertyChanged("puesto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trabajador_pagos", Storage="_trabajador", ThisKey="id_trabajador", OtherKey="id_trabajador", IsForeignKey=true)]
		public trabajador trabajador
		{
			get
			{
				return this._trabajador.Entity;
			}
			set
			{
				trabajador previousValue = this._trabajador.Entity;
				if (((previousValue != value) 
							|| (this._trabajador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._trabajador.Entity = null;
						previousValue.pagos.Remove(this);
					}
					this._trabajador.Entity = value;
					if ((value != null))
					{
						value.pagos.Add(this);
						this._id_trabajador = value.id_trabajador;
					}
					else
					{
						this._id_trabajador = default(int);
					}
					this.SendPropertyChanged("trabajador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
	public partial class usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _usuario;
		
		private string _passwd;
		
		private string _estado;
		
		private string _tipo_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnpasswdChanging(string value);
    partial void OnpasswdChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Ontipo_usuarioChanging(string value);
    partial void Ontipo_usuarioChanged();
    #endregion
		
		public usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NChar(10)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwd", DbType="NChar(10)")]
		public string passwd
		{
			get
			{
				return this._passwd;
			}
			set
			{
				if ((this._passwd != value))
				{
					this.OnpasswdChanging(value);
					this.SendPropertyChanging();
					this._passwd = value;
					this.SendPropertyChanged("passwd");
					this.OnpasswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario", DbType="NChar(20)")]
		public string tipo_usuario
		{
			get
			{
				return this._tipo_usuario;
			}
			set
			{
				if ((this._tipo_usuario != value))
				{
					this.Ontipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._tipo_usuario = value;
					this.SendPropertyChanged("tipo_usuario");
					this.Ontipo_usuarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.puesto")]
	public partial class puesto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_puesto;
		
		private string _puesto1;
		
		private string _cargo;
		
		private string _tareas;
		
		private EntitySet<pagos> _pagos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_puestoChanging(int value);
    partial void Onid_puestoChanged();
    partial void Onpuesto1Changing(string value);
    partial void Onpuesto1Changed();
    partial void OncargoChanging(string value);
    partial void OncargoChanged();
    partial void OntareasChanging(string value);
    partial void OntareasChanged();
    #endregion
		
		public puesto()
		{
			this._pagos = new EntitySet<pagos>(new Action<pagos>(this.attach_pagos), new Action<pagos>(this.detach_pagos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_puesto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_puesto
		{
			get
			{
				return this._id_puesto;
			}
			set
			{
				if ((this._id_puesto != value))
				{
					this.Onid_puestoChanging(value);
					this.SendPropertyChanging();
					this._id_puesto = value;
					this.SendPropertyChanged("id_puesto");
					this.Onid_puestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="puesto", Storage="_puesto1", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string puesto1
		{
			get
			{
				return this._puesto1;
			}
			set
			{
				if ((this._puesto1 != value))
				{
					this.Onpuesto1Changing(value);
					this.SendPropertyChanging();
					this._puesto1 = value;
					this.SendPropertyChanged("puesto1");
					this.Onpuesto1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this.OncargoChanging(value);
					this.SendPropertyChanging();
					this._cargo = value;
					this.SendPropertyChanged("cargo");
					this.OncargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tareas", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string tareas
		{
			get
			{
				return this._tareas;
			}
			set
			{
				if ((this._tareas != value))
				{
					this.OntareasChanging(value);
					this.SendPropertyChanging();
					this._tareas = value;
					this.SendPropertyChanged("tareas");
					this.OntareasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="puesto_pagos", Storage="_pagos", ThisKey="id_puesto", OtherKey="id_puesto")]
		public EntitySet<pagos> pagos
		{
			get
			{
				return this._pagos;
			}
			set
			{
				this._pagos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pagos(pagos entity)
		{
			this.SendPropertyChanging();
			entity.puesto = this;
		}
		
		private void detach_pagos(pagos entity)
		{
			this.SendPropertyChanging();
			entity.puesto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sueldo")]
	public partial class sueldo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sueldo;
		
		private int _id_trabajador;
		
		private int _id_puesto;
		
		private double _sueldo1;
		
		private EntityRef<trabajador> _trabajador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sueldoChanging(int value);
    partial void Onid_sueldoChanged();
    partial void Onid_trabajadorChanging(int value);
    partial void Onid_trabajadorChanged();
    partial void Onid_puestoChanging(int value);
    partial void Onid_puestoChanged();
    partial void Onsueldo1Changing(double value);
    partial void Onsueldo1Changed();
    #endregion
		
		public sueldo()
		{
			this._trabajador = default(EntityRef<trabajador>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sueldo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sueldo
		{
			get
			{
				return this._id_sueldo;
			}
			set
			{
				if ((this._id_sueldo != value))
				{
					this.Onid_sueldoChanging(value);
					this.SendPropertyChanging();
					this._id_sueldo = value;
					this.SendPropertyChanged("id_sueldo");
					this.Onid_sueldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trabajador", DbType="Int NOT NULL")]
		public int id_trabajador
		{
			get
			{
				return this._id_trabajador;
			}
			set
			{
				if ((this._id_trabajador != value))
				{
					if (this._trabajador.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_trabajadorChanging(value);
					this.SendPropertyChanging();
					this._id_trabajador = value;
					this.SendPropertyChanged("id_trabajador");
					this.Onid_trabajadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_puesto", DbType="Int NOT NULL")]
		public int id_puesto
		{
			get
			{
				return this._id_puesto;
			}
			set
			{
				if ((this._id_puesto != value))
				{
					this.Onid_puestoChanging(value);
					this.SendPropertyChanging();
					this._id_puesto = value;
					this.SendPropertyChanged("id_puesto");
					this.Onid_puestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sueldo", Storage="_sueldo1", DbType="Float NOT NULL")]
		public double sueldo1
		{
			get
			{
				return this._sueldo1;
			}
			set
			{
				if ((this._sueldo1 != value))
				{
					this.Onsueldo1Changing(value);
					this.SendPropertyChanging();
					this._sueldo1 = value;
					this.SendPropertyChanged("sueldo1");
					this.Onsueldo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trabajador_sueldo", Storage="_trabajador", ThisKey="id_trabajador", OtherKey="id_trabajador", IsForeignKey=true)]
		public trabajador trabajador
		{
			get
			{
				return this._trabajador.Entity;
			}
			set
			{
				trabajador previousValue = this._trabajador.Entity;
				if (((previousValue != value) 
							|| (this._trabajador.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._trabajador.Entity = null;
						previousValue.sueldo.Remove(this);
					}
					this._trabajador.Entity = value;
					if ((value != null))
					{
						value.sueldo.Add(this);
						this._id_trabajador = value.id_trabajador;
					}
					else
					{
						this._id_trabajador = default(int);
					}
					this.SendPropertyChanged("trabajador");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trabajador")]
	public partial class trabajador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_trabajador;
		
		private string _nombre;
		
		private string _apellido_pat;
		
		private string _apellido_mat;
		
		private string _direccion;
		
		private string _telefono;
		
		private int _num_empleado;
		
		private int _id_usuario;
		
		private int _id_puesto;
		
		private EntitySet<pagos> _pagos;
		
		private EntitySet<sueldo> _sueldo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_trabajadorChanging(int value);
    partial void Onid_trabajadorChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onapellido_patChanging(string value);
    partial void Onapellido_patChanged();
    partial void Onapellido_matChanging(string value);
    partial void Onapellido_matChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Onnum_empleadoChanging(int value);
    partial void Onnum_empleadoChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_puestoChanging(int value);
    partial void Onid_puestoChanged();
    #endregion
		
		public trabajador()
		{
			this._pagos = new EntitySet<pagos>(new Action<pagos>(this.attach_pagos), new Action<pagos>(this.detach_pagos));
			this._sueldo = new EntitySet<sueldo>(new Action<sueldo>(this.attach_sueldo), new Action<sueldo>(this.detach_sueldo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trabajador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_trabajador
		{
			get
			{
				return this._id_trabajador;
			}
			set
			{
				if ((this._id_trabajador != value))
				{
					this.Onid_trabajadorChanging(value);
					this.SendPropertyChanging();
					this._id_trabajador = value;
					this.SendPropertyChanged("id_trabajador");
					this.Onid_trabajadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_pat", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string apellido_pat
		{
			get
			{
				return this._apellido_pat;
			}
			set
			{
				if ((this._apellido_pat != value))
				{
					this.Onapellido_patChanging(value);
					this.SendPropertyChanging();
					this._apellido_pat = value;
					this.SendPropertyChanged("apellido_pat");
					this.Onapellido_patChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_mat", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string apellido_mat
		{
			get
			{
				return this._apellido_mat;
			}
			set
			{
				if ((this._apellido_mat != value))
				{
					this.Onapellido_matChanging(value);
					this.SendPropertyChanging();
					this._apellido_mat = value;
					this.SendPropertyChanged("apellido_mat");
					this.Onapellido_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_empleado", DbType="Int NOT NULL")]
		public int num_empleado
		{
			get
			{
				return this._num_empleado;
			}
			set
			{
				if ((this._num_empleado != value))
				{
					this.Onnum_empleadoChanging(value);
					this.SendPropertyChanging();
					this._num_empleado = value;
					this.SendPropertyChanged("num_empleado");
					this.Onnum_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_puesto", DbType="Int NOT NULL")]
		public int id_puesto
		{
			get
			{
				return this._id_puesto;
			}
			set
			{
				if ((this._id_puesto != value))
				{
					this.Onid_puestoChanging(value);
					this.SendPropertyChanging();
					this._id_puesto = value;
					this.SendPropertyChanged("id_puesto");
					this.Onid_puestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trabajador_pagos", Storage="_pagos", ThisKey="id_trabajador", OtherKey="id_trabajador")]
		public EntitySet<pagos> pagos
		{
			get
			{
				return this._pagos;
			}
			set
			{
				this._pagos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trabajador_sueldo", Storage="_sueldo", ThisKey="id_trabajador", OtherKey="id_trabajador")]
		public EntitySet<sueldo> sueldo
		{
			get
			{
				return this._sueldo;
			}
			set
			{
				this._sueldo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pagos(pagos entity)
		{
			this.SendPropertyChanging();
			entity.trabajador = this;
		}
		
		private void detach_pagos(pagos entity)
		{
			this.SendPropertyChanging();
			entity.trabajador = null;
		}
		
		private void attach_sueldo(sueldo entity)
		{
			this.SendPropertyChanging();
			entity.trabajador = this;
		}
		
		private void detach_sueldo(sueldo entity)
		{
			this.SendPropertyChanging();
			entity.trabajador = null;
		}
	}
}
#pragma warning restore 1591
