<?xml version="1.0" encoding="utf-8"?><Database Name="ejercicio" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LUDWIG-ASUS;Initial Catalog=ejercicio;Integrated Security=True" SettingsObjectName="LINQ5.Properties.Settings" SettingsPropertyName="LinqString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.usuarios" Member="usuarios">
    <Type Name="usuarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="passwd" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="tipo_usuario" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.trabajador" Member="trabajador">
    <Type Name="trabajador">
      <Column Name="id_trabajador" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_pat" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_mat" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="num_empleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_puesto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>